# Generated by Django 5.1.15 on 2026-09-17 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='contenu')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name="date d'envoi")),
                ('statut', models.CharField(choices=[('ENVOYEE', 'Envoyée'), ('LUE', 'Lue'), ('ECHOUEE', 'Échouée')], default='ENVOYEE', max_length=10, verbose_name='statut')),
                ('adresse_email', models.EmailField(max_length=254, verbose_name='adresse email')),
                ('objet', models.CharField(max_length=200, verbose_name='objet')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='destinataire')),
            ],
            options={
                'verbose_name': 'notification email',
                'verbose_name_plural': 'notifications email',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='contenu')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name="date d'envoi")),
                ('statut', models.CharField(choices=[('ENVOYEE', 'Envoyée'), ('LUE', 'Lue'), ('ECHOUEE', 'Échouée')], default='ENVOYEE', max_length=10, verbose_name='statut')),
                ('device_token', models.CharField(max_length=255, verbose_name="jeton de l'appareil")),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='destinataire')),
            ],
            options={
                'verbose_name': 'notification push',
                'verbose_name_plural': 'notifications push',
                'ordering': ['-date_envoi'],
            },
        ),
    ]
