# Generated by Django 5.1.15 on 2026-09-17 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nom', models.CharField(max_length=150, verbose_name='nom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='accès admin Django')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'compte utilisateur',
                'verbose_name_plural': 'comptes utilisateurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('compteutilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'administrateur',
                'verbose_name_plural': 'administrateurs',
                'ordering': ['nom'],
            },
            bases=('comptes.compteutilisateur',),
        ),
        migrations.CreateModel(
            name='Professionnel',
            fields=[
                ('compteutilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('specialite', models.CharField(choices=[('PSYCHOLOGUE', 'Psychologue'), ('ASSISTANT_SOCIAL', 'Assistant social'), ('COACH_DEVELOPPEMENT', 'Coach en développement personnel'), ('SOPHROLOGUE', 'Sophrologue'), ('MEDIATEUR_FAMILIAL', 'Médiateur familial'), ('COACH_SPORTIF', 'Coach sportif')], max_length=32, verbose_name='spécialité')),
                ('ville', models.CharField(max_length=100, verbose_name='ville')),
                ('langue', models.CharField(max_length=100, verbose_name='langue')),
                ('tarif_indicatif', models.FloatField(verbose_name='tarif indicatif (FCFA)')),
                ('statut_validation', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=12, verbose_name='statut de validation')),
            ],
            options={
                'verbose_name': 'professionnel',
                'verbose_name_plural': 'professionnels',
                'ordering': ['ville', 'nom'],
            },
            bases=('comptes.compteutilisateur',),
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('compteutilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('prenom', models.CharField(max_length=150, verbose_name='prénom')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'ordering': ['nom', 'prenom'],
            },
            bases=('comptes.compteutilisateur',),
        ),
    ]
