# Generated by Django 5.1.15 on 2026-09-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='pseudonyme',
            field=models.CharField(default='', editable=False, max_length=50, unique=True, verbose_name='pseudonyme'),
            preserve_default=False,
        ),
    ]
