# Generated by Django 5.1.15 on 2026-09-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_utilisateur_pseudonyme'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionnel',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date de validation'),
        ),
        migrations.AddField(
            model_name='professionnel',
            name='presentation',
            field=models.TextField(blank=True, max_length=500, verbose_name='présentation'),
        ),
    ]
