# Generated by Django 5.1.15 on 2026-09-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0003_professionnel_date_validation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compteutilisateur',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, verbose_name='préférences'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='ville',
            field=models.CharField(blank=True, max_length=100, verbose_name='ville'),
        ),
    ]
