# Generated by Django 5.1.15 on 2026-09-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0004_compteutilisateur_preferences_utilisateur_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionnel',
            name='adresse_cabinet',
            field=models.CharField(blank=True, max_length=150, verbose_name='adresse du cabinet'),
        ),
        migrations.AddField(
            model_name='professionnel',
            name='consultation_cabinet',
            field=models.BooleanField(default=False, verbose_name='consultation en cabinet'),
        ),
        migrations.AddField(
            model_name='professionnel',
            name='consultation_distance',
            field=models.BooleanField(default=False, verbose_name='consultation à distance'),
        ),
        migrations.AddField(
            model_name='professionnel',
            name='domaines',
            field=models.JSONField(blank=True, default=list, verbose_name="domaines d'accompagnement"),
        ),
    ]
