# Generated by Django 5.1.15 on 2026-09-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0005_professionnel_domaines_modalites'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionnel',
            name='accepte_demandes',
            field=models.BooleanField(default=True, verbose_name='accepte de nouvelles demandes'),
        ),
    ]
