# Generated by Django 5.1.15 on 2026-09-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0006_professionnel_accepte_demandes'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='forum_suspendu_jusqu_au',
            field=models.DateTimeField(blank=True, null=True, verbose_name='forum suspendu jusqu’au'),
        ),
    ]
