# Generated by Django 5.1.15 on 2026-10-01 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0007_utilisateur_forum_suspendu_jusqu_au'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonneConfiance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=80, verbose_name='prénom')),
                ('lien', models.CharField(blank=True, max_length=60, verbose_name='lien')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('accord_confirme', models.BooleanField(default=False, verbose_name='accord de la personne confirmé')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True, verbose_name='mise à jour')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personne_confiance', to='comptes.utilisateur', verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'personne de confiance',
                'verbose_name_plural': 'personnes de confiance',
            },
        ),
        migrations.CreateModel(
            name='AlerteConfiance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(max_length=10, verbose_name='canal')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='comptes.personneconfiance', verbose_name='personne de confiance')),
            ],
            options={
                'verbose_name': 'alerte à la personne de confiance',
                'verbose_name_plural': 'alertes à la personne de confiance',
                'ordering': ['-date'],
            },
        ),
    ]
