# Generated by Django 5.1.15 on 2026-10-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0008_personneconfiance_alerteconfiance'),
    ]

    operations = [
        migrations.AddField(
            model_name='personneconfiance',
            name='alerte_automatique',
            field=models.BooleanField(default=False, verbose_name='alerte automatique en cas de risque vital'),
        ),
    ]
