# Generated by Django 5.1.15 on 2026-09-17 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LieuDetente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='nom')),
                ('ville', models.CharField(max_length=100, verbose_name='ville')),
                ('description', models.TextField(verbose_name='description')),
                ('categorie', models.CharField(max_length=100, verbose_name='catégorie')),
            ],
            options={
                'verbose_name': 'lieu de détente',
                'verbose_name_plural': 'lieux de détente',
                'ordering': ['ville', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='titre')),
                ('type_ressource', models.CharField(choices=[('ARTICLE', 'Article'), ('EXERCICE', 'Exercice'), ('PODCAST', 'Podcast')], max_length=10, verbose_name='type de ressource')),
                ('contenu', models.TextField(verbose_name='contenu')),
                ('thematique', models.CharField(max_length=100, verbose_name='thématique')),
            ],
            options={
                'verbose_name': 'ressource',
                'verbose_name_plural': 'ressources',
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='comptes.utilisateur', verbose_name='utilisateur')),
                ('ressource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='ressources.ressource', verbose_name='ressource')),
            ],
            options={
                'verbose_name': 'favori',
                'verbose_name_plural': 'favoris',
                'ordering': ['-date_ajout'],
                'constraints': [models.UniqueConstraint(fields=('utilisateur', 'ressource'), name='favori_unique_par_utilisateur_et_ressource')],
            },
        ),
    ]
