# Generated by Django 5.1.15 on 2026-09-19 15:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lieudetente',
            name='acces_libre',
            field=models.BooleanField(default=True, verbose_name='accès libre'),
        ),
        migrations.AddField(
            model_name='lieudetente',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='lieudetente',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='longitude'),
        ),
        migrations.AddField(
            model_name='ressource',
            name='date_publication',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='date de publication'),
        ),
        migrations.AddField(
            model_name='ressource',
            name='duree_lecture',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='durée (minutes)'),
        ),
    ]
