# Generated by Django 5.1.15 on 2026-09-17 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('type_evaluation', models.CharField(choices=[('STRESS', 'Stress'), ('ANXIETE', 'Anxiété'), ('FATIGUE', 'Fatigue')], max_length=10, verbose_name="type d'évaluation")),
                ('score_de_tendance', models.FloatField(verbose_name='score de tendance')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_evaluations', to='comptes.utilisateur', verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'auto-évaluation',
                'verbose_name_plural': 'auto-évaluations',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SuiviHumeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('score_humeur', models.CharField(choices=[('TRES_MAL', 'Très mal'), ('MAL', 'Mal'), ('NEUTRE', 'Neutre'), ('BIEN', 'Bien'), ('TRES_BIEN', 'Très bien')], max_length=10, verbose_name='humeur')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis_humeur', to='comptes.utilisateur', verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': "suivi d'humeur",
                'verbose_name_plural': "suivis d'humeur",
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('utilisateur', 'date'), name='une_entree_par_jour_et_par_utilisateur')],
            },
        ),
    ]
