# Generated by Django 5.1.15 on 2026-09-17 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_evaluation', models.CharField(choices=[('STRESS', 'Stress'), ('ANXIETE', 'Anxiété'), ('FATIGUE', 'Fatigue')], max_length=10, verbose_name="type d'évaluation")),
                ('libelle', models.CharField(max_length=255, verbose_name='libellé')),
                ('ordre', models.PositiveSmallIntegerField(verbose_name='ordre')),
            ],
            options={
                'verbose_name': "question d'évaluation",
                'verbose_name_plural': "questions d'évaluation",
                'ordering': ['type_evaluation', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='OptionReponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150, verbose_name='libellé')),
                ('valeur', models.PositiveSmallIntegerField(verbose_name='valeur')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='suivi.questionevaluation', verbose_name='question')),
            ],
            options={
                'verbose_name': 'option de réponse',
                'verbose_name_plural': 'options de réponse',
                'ordering': ['question', 'valeur'],
                'constraints': [models.CheckConstraint(condition=models.Q(('valeur__gte', 0), ('valeur__lte', 4)), name='valeur_option_entre_0_et_4')],
            },
        ),
    ]
