# Generated by Django 5.1.15 on 2026-09-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0002_questionevaluation_optionreponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='suivihumeur',
            name='etiquettes',
            field=models.CharField(blank=True, max_length=255, verbose_name='étiquettes'),
        ),
    ]
