# Generated by Django 5.1.15 on 2026-09-30 12:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0006_professionnel_accepte_demandes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesMiseEnRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyen', models.CharField(choices=[('WAVE', 'Wave'), ('ORANGE_MONEY', 'Orange Money'), ('FREE_MONEY', 'Free Money'), ('OFFERT', 'Offert par Sen Suivi')], max_length=12, verbose_name='moyen de paiement')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de paiement'), ('ACTIF', 'Actif'), ('ECHEC', 'Échec du paiement')], default='EN_ATTENTE', max_length=10, verbose_name='statut')),
                ('date_debut', models.DateField(default=django.utils.timezone.localdate, verbose_name='début')),
                ('date_fin', models.DateField(verbose_name='fin')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='référence')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acces_mise_en_relation', to='comptes.utilisateur', verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'accès à la mise en relation',
                'verbose_name_plural': 'accès à la mise en relation',
                'ordering': ['-date_creation'],
            },
        ),
    ]
