# Generated by Django 5.1.15 on 2026-09-17 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée')], default='EN_ATTENTE', max_length=10, verbose_name='statut')),
                ('message', models.TextField(verbose_name='message')),
                ('professionnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_contact_recues', to='comptes.professionnel', verbose_name='professionnel')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_contact_envoyees', to='comptes.utilisateur', verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'demande de contact',
                'verbose_name_plural': 'demandes de contact',
                'ordering': ['-date'],
            },
        ),
    ]
