# Generated by Django 5.1.15 on 2026-09-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandecontact',
            name='date_reponse',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date de réponse'),
        ),
        migrations.AlterField(
            model_name='demandecontact',
            name='message',
            field=models.TextField(blank=True, verbose_name='message'),
        ),
    ]
