# Generated by Django 5.1.15 on 2026-09-30 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0002_demandecontact_date_reponse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(max_length=2000, verbose_name='contenu')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('lu_le', models.DateTimeField(blank=True, null=True, verbose_name='lu le')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_relation', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='relations.demandecontact', verbose_name='demande')),
            ],
            options={
                'verbose_name': 'message de mise en relation',
                'verbose_name_plural': 'messages de mise en relation',
                'ordering': ['date', 'id'],
            },
        ),
    ]
