# Generated by Django 5.1.15 on 2026-09-17 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='contenu')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('statut_moderation', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VISIBLE', 'Visible'), ('MASQUE', 'Masqué'), ('SUPPRIME', 'Supprimé')], default='EN_ATTENTE', max_length=10, verbose_name='statut de modération')),
                ('moderateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications_moderees', to='comptes.administrateur', verbose_name='modérateur')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications_forum', to='comptes.utilisateur', verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'publication du forum',
                'verbose_name_plural': 'publications du forum',
                'ordering': ['-date'],
            },
        ),
    ]
