# Generated by Django 5.1.15 on 2026-09-20 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0004_compteutilisateur_preferences_utilisateur_ville'),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationforum',
            name='thematique',
            field=models.CharField(choices=[('STRESS', 'Stress'), ('SOMMEIL', 'Sommeil'), ('RELATIONS', 'Relations'), ('TRAVAIL', 'Travail'), ('DEUIL', 'Deuil')], default='STRESS', max_length=10, verbose_name='thématique'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicationforum',
            name='titre',
            field=models.CharField(default='', max_length=150, verbose_name='titre'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CommentaireForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='contenu')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('statut_moderation', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VISIBLE', 'Visible'), ('MASQUE', 'Masqué'), ('SUPPRIME', 'Supprimé')], default='EN_ATTENTE', max_length=10, verbose_name='statut de modération')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='forum.publicationforum', verbose_name='publication')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires_forum', to='comptes.utilisateur', verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'commentaire du forum',
                'verbose_name_plural': 'commentaires du forum',
                'ordering': ['date'],
            },
        ),
    ]
