# Generated by Django 5.1.15 on 2026-09-20 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0004_compteutilisateur_preferences_utilisateur_ville'),
        ('forum', '0002_publicationforum_thematique_publicationforum_titre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaireforum',
            name='moderateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commentaires_moderes', to='comptes.administrateur', verbose_name='modérateur'),
        ),
    ]
