# Generated by Django 5.1.15 on 2026-09-30 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0007_utilisateur_forum_suspendu_jusqu_au'),
        ('forum', '0003_commentaireforum_moderateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaireforum',
            name='statut_moderation',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VISIBLE', 'Visible'), ('MASQUE', 'Masqué'), ('SUPPRIME', 'Supprimé'), ('BLOQUE', 'Bloqué')], default='EN_ATTENTE', max_length=10, verbose_name='statut de modération'),
        ),
        migrations.AlterField(
            model_name='publicationforum',
            name='statut_moderation',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VISIBLE', 'Visible'), ('MASQUE', 'Masqué'), ('SUPPRIME', 'Supprimé'), ('BLOQUE', 'Bloqué')], default='EN_ATTENTE', max_length=10, verbose_name='statut de modération'),
        ),
        migrations.CreateModel(
            name='ModerationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('PUBLIER', 'Publié'), ('PUBLIER_ACCOMPAGNER', 'Publié et accompagné'), ('BLOQUER', 'Bloqué'), ('BLOQUER_PRIORITAIRE', 'Bloqué, priorité haute'), ('BLOQUER_SILENCIEUX', 'Bloqué sans message (spam)'), ('ATTENTE_HUMAINE', 'En attente de validation humaine')], max_length=20, verbose_name='décision automatique')),
                ('categorie', models.CharField(max_length=24, verbose_name='catégorie')),
                ('gravite', models.PositiveSmallIntegerField(default=0, verbose_name='gravité')),
                ('raison', models.CharField(blank=True, max_length=255, verbose_name='raison')),
                ('extrait', models.CharField(blank=True, max_length=500, verbose_name='extrait')),
                ('niveau', models.CharField(max_length=10, verbose_name='niveau')),
                ('message_auteur', models.TextField(blank=True, verbose_name="message à l'auteur")),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('a_traiter', models.BooleanField(default=False, verbose_name='dans la file des administrateurs')),
                ('priorite', models.PositiveSmallIntegerField(default=0, verbose_name='priorité')),
                ('motif_contestation', models.TextField(blank=True, verbose_name='motif de contestation')),
                ('date_contestation', models.DateTimeField(blank=True, null=True, verbose_name='date de contestation')),
                ('decision_humaine', models.CharField(blank=True, choices=[('PUBLIER', 'Publié par un administrateur'), ('BLOQUER', 'Bloqué par un administrateur'), ('CLASSER', 'Vu, aucune action')], max_length=10, verbose_name='décision humaine')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='date de traitement')),
                ('commentaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderations', to='forum.commentaireforum', verbose_name='commentaire')),
                ('moderateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_moderation', to='comptes.administrateur', verbose_name='modérateur')),
                ('publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderations', to='forum.publicationforum', verbose_name='publication')),
            ],
            options={
                'verbose_name': 'décision de modération',
                'verbose_name_plural': 'décisions de modération',
                'ordering': ['-priorite', 'date'],
            },
        ),
    ]
