# Generated by Django 5.1.15 on 2026-09-17 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('consentement_conservation', models.BooleanField(default=False, verbose_name='consentement à la conservation')),
            ],
            options={
                'verbose_name': 'conversation avec le chatbot',
                'verbose_name_plural': 'conversations avec le chatbot',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MessageChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='contenu')),
                ('type_expediteur', models.CharField(choices=[('UTILISATEUR', 'Utilisateur'), ('BOT', 'Bot')], max_length=12, verbose_name="type d'expéditeur")),
                ('source_reponse', models.CharField(blank=True, choices=[('REGLE', 'Règle'), ('RAG', 'RAG')], help_text='Uniquement pour les messages du bot (REGLE pour les niveaux 0 et 1, RAG pour le niveau 2).', max_length=6, null=True, verbose_name='source de la réponse')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name="date d'envoi")),
            ],
            options={
                'verbose_name': 'message du chatbot',
                'verbose_name_plural': 'messages du chatbot',
                'ordering': ['date_envoi'],
            },
        ),
    ]
