# Generated by Django 5.1.15 on 2026-09-17 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatbot', '0001_initial'),
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationchatbot',
            name='utilisateur',
            field=models.ForeignKey(blank=True, help_text='Vide pour une conversation anonyme : le chatbot est accessible sans compte.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations_chatbot', to='comptes.utilisateur', verbose_name='utilisateur'),
        ),
        migrations.AddField(
            model_name='messagechatbot',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.conversationchatbot', verbose_name='conversation'),
        ),
    ]
