# Generated by Django 5.1.15 on 2026-09-27 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_initial'),
        ('ressources', '0002_lieudetente_acces_libre_lieudetente_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagechatbot',
            name='ressource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ressources.ressource', verbose_name='ressource suggérée'),
        ),
        migrations.AddField(
            model_name='messagechatbot',
            name='urgence',
            field=models.BooleanField(default=False, help_text='Vrai si la réponse du bot renvoyait vers les numéros d’urgence.', verbose_name='alerte de détresse'),
        ),
    ]
