# Generated by Django 5.1.15 on 2026-09-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_messages_urgence_ressource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagechatbot',
            name='source_reponse',
            field=models.CharField(blank=True, choices=[('REGLE', 'Règle'), ('RAG', 'RAG'), ('GENERATION', 'Génération encadrée')], help_text='Uniquement pour les messages du bot : REGLE pour les niveaux 0 et 1, RAG pour le niveau 2a, GENERATION pour une réponse du modèle de langage validée (niveau 2b).', max_length=10, null=True, verbose_name='source de la réponse'),
        ),
    ]
