# Generated by Django 5.1.15 on 2026-10-01 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_source_generation'),
        ('comptes', '0009_personneconfiance_alerte_automatique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalementRisque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(choices=[('RISQUE_VITAL', 'Risque pour sa vie'), ('DETRESSE', 'Détresse intense'), ('DANGER_AUTRUI', 'Danger pour autrui'), ('VIOLENCES', 'Violences subies')], max_length=14, verbose_name='nature')),
                ('personne_confiance_prevenue', models.BooleanField(default=False, verbose_name='personne de confiance prévenue')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements_risque', to='comptes.utilisateur', verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'signalement de situation à risque',
                'verbose_name_plural': 'signalements de situations à risque',
                'ordering': ['-date'],
            },
        ),
    ]
