# Generated by Django 5.1.15 on 2026-10-02 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_signalementrisque'),
        ('comptes', '0009_personneconfiance_alerte_automatique'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalementrisque',
            name='date_suivi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date du suivi'),
        ),
        migrations.AddField(
            model_name='signalementrisque',
            name='suivi_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_suivis', to='comptes.administrateur', verbose_name='suivi par'),
        ),
    ]
