// Registre figé des icônes.
// Seul ce fichier importe depuis @lucide/angular : tout le reste de
// l'application passe par <ss-icon>, jamais par un import Lucide direct.
import {
  LucideActivity,
  LucideArrowLeft,
  LucideLock,
  LucideMail,
  LucideArrowRight,
  LucideBookOpen,
  LucideBookmark,
  LucideCalendarCheck,
  LucideChartLine,
  LucideChevronLeft,
  LucideChevronRight,
  LucideCircleAlert,
  LucideCircleCheck,
  LucideClock,
  LucideEye,
  LucideEyeOff,
  LucideFileText,
  LucideHeart,
  LucideHouse,
  LucideLocateFixed,
  LucideMap,
  LucideMapPin,
  LucideMessageCircle,
  LucideMic,
  LucideMinus,
  LucideNavigation,
  LucidePhone,
  LucidePlus,
  LucideSearch,
  LucideSettings,
  LucideShare2,
  LucideTicket,
  LucideUser,
  LucideX,
} from '@lucide/angular';

export const ICONES = {
  oeil: LucideEye,
  'oeil-barre': LucideEyeOff,
  alerte: LucideCircleAlert,
  accueil: LucideHouse,
  journal: LucideChartLine,
  ressources: LucideBookOpen,
  lieux: LucideMapPin,
  parametres: LucideSettings,
  chat: LucideMessageCircle,
  fleche: LucideArrowRight,
  telephone: LucidePhone,
  'fleche-gauche': LucideArrowLeft,
  fermer: LucideX,
  recherche: LucideSearch,
  horloge: LucideClock,
  coeur: LucideHeart,
  article: LucideFileText,
  exercice: LucideActivity,
  podcast: LucideMic,
  calendrier: LucideCalendarCheck,
  'marque-page': LucideBookmark,
  partage: LucideShare2,
  'chevron-droite': LucideChevronRight,
  'chevron-gauche': LucideChevronLeft,
  carte: LucideMap,
  ticket: LucideTicket,
  verifie: LucideCircleCheck,
  itineraire: LucideNavigation,
  plus: LucidePlus,
  moins: LucideMinus,
  localiser: LucideLocateFixed,
  utilisateur: LucideUser,
  courriel: LucideMail,
  cadenas: LucideLock,
} as const;

export type NomIcone = keyof typeof ICONES;
